[2024-03-10T17:06:11.233+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=test_data_access/run_id=manual__2024-03-10T17:06:10.004559+00:00/task_id=test_read_data permission to 509
[2024-03-10T17:06:11.234+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=test_data_access/run_id=manual__2024-03-10T17:06:10.004559+00:00/task_id=test_read_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=test_data_access/run_id=manual__2024-03-10T17:06:10.004559+00:00/task_id=test_read_data'
[2024-03-10T17:06:11.258+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=test_data_access/run_id=manual__2024-03-10T17:06:10.004559+00:00/task_id=test_read_data permission to 509
[2024-03-10T17:06:11.260+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=test_data_access/run_id=manual__2024-03-10T17:06:10.004559+00:00/task_id=test_read_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=test_data_access/run_id=manual__2024-03-10T17:06:10.004559+00:00/task_id=test_read_data'
[2024-03-10T17:06:11.287+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_data_access.test_read_data manual__2024-03-10T17:06:10.004559+00:00 [queued]>
[2024-03-10T17:06:11.297+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_data_access.test_read_data manual__2024-03-10T17:06:10.004559+00:00 [queued]>
[2024-03-10T17:06:11.298+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2024-03-10T17:06:11.313+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): test_read_data> on 2024-03-10 17:06:10.004559+00:00
[2024-03-10T17:06:11.317+0000] {standard_task_runner.py:57} INFO - Started process 365 to run task
[2024-03-10T17:06:11.320+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'test_data_access', 'test_read_data', 'manual__2024-03-10T17:06:10.004559+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/test_data_access.py', '--cfg-path', '/tmp/tmp005te_mw']
[2024-03-10T17:06:11.321+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask test_read_data
[2024-03-10T17:06:11.372+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=test_data_access/run_id=manual__2024-03-10T17:06:10.004559+00:00/task_id=test_read_data permission to 509
[2024-03-10T17:06:11.373+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=test_data_access/run_id=manual__2024-03-10T17:06:10.004559+00:00/task_id=test_read_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=test_data_access/run_id=manual__2024-03-10T17:06:10.004559+00:00/task_id=test_read_data'
[2024-03-10T17:06:11.375+0000] {task_command.py:410} INFO - Running <TaskInstance: test_data_access.test_read_data manual__2024-03-10T17:06:10.004559+00:00 [running]> on host f95f5ac280e4
[2024-03-10T17:06:11.466+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_data_access' AIRFLOW_CTX_TASK_ID='test_read_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T17:06:10.004559+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-10T17:06:10.004559+00:00'
[2024-03-10T17:06:11.468+0000] {logging_mixin.py:149} INFO - El archivo penguins_size.csv existe en /opt/***/data.
[2024-03-10T17:06:11.468+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-03-10T17:06:11.479+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=test_data_access, task_id=test_read_data, execution_date=20240310T170610, start_date=20240310T170611, end_date=20240310T170611
[2024-03-10T17:06:11.533+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2024-03-10T17:06:11.551+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
